Add docker
am29-10/java-shareit pull request #6
Opened 2022-12-06 18:22 UTC by am29-10

2022-12-07 19:46 UTC, sergeymamonov requested changes
Класс BookingServiceImpl строки 99 - 102 такая валидация не требуется, так как в этом сервисе мы работаем уже с валидными данными.
Класс ItemServiceImpl строки 110-111 itemRepository.findById(id).isPresent() и на следующей строке itemRepository.findById(id).get() - получается два раза запрашиваете БД, чтобы получить одно значение. Не нужно так делать. Нужно минимизировать количество обращений к БД.

2022-12-07 19:46 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +		return bookingClient.getBookings(userId, state, from, size);
Если я сделаю запрос в сервис gateway с невалидными данными, например page = -1, size = - 1, то эти невалидные данные уйдут в основной сервис. Тогда какой смысл от сервиса gateway?

2022-12-07 19:46 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/ShareItApp.java
> +		System.getProperties().put("server.port", 9090);
Лучше всю конфигурацию выносить из кода в конфигурационные файлы. И плюс посмотрите в этом сервисе файл application.properties, там тоже указан порт.

2022-12-08 17:00 UTC, am29-10 commented on server/src/main/java/ru/practicum/shareit/ShareItApp.java
> +		System.getProperties().put("server.port", 9090);
Ранее порт принимал номер 8080, хотя в конфигурационном файле проставлял 9090, поэтому вынес в главный метод объявление порта. Сейчас эта проблема решилась

2022-12-09 18:02 UTC, sergeymamonov approved these changes

2022-12-09 18:02 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        //validate(getItemById(id));
Закомментированного кода быть не должно.

2022-12-15 09:01 UTC, merged